name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build
        env:
          NODE_ENV: production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          echo "Starting deployment..."
          # Deploy non-HTML/JSON files with long cache
          aws s3 sync out/ s3://thecogniscentai.com \
            --delete \
            --cache-control "max-age=31536000,public" \
            --exclude "*.html" \
            --exclude "*.json"
          
          # Deploy HTML and JSON files without caching
          aws s3 sync out/ s3://thecogniscentai.com \
            --delete \
            --cache-control "no-cache,no-store,must-revalidate" \
            --exclude "*" \
            --include "*.html" \
            --include "*.json"
          
          echo "Deployment complete!"

      - name: Invalidate CloudFront
        run: |
          echo "Creating CloudFront invalidation..."
          # Get CloudFront distribution ID from secrets
          CLOUDFRONT_ID="${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
          
          # Create invalidation
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_ID \
            --paths "/*"
          
          echo "Invalidation created!"

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          aws s3 ls s3://thecogniscentai.com --recursive
          
          # Check if index.html exists
          aws s3api head-object \
            --bucket thecogniscentai.com \
            --key index.html || exit 1